version: '3.1'
volumes:
    mongo_data:
services:
    server:
        build: ./server
        restart: unless-stopped
        image: server:latest
        ports:
            - 8000:8000
        volumes:
            - ./server:/user/src/app
        links:
            - mongo
        command: yarn start
        tty: true
        stdin_open: true

    client:
        build: ./client
        restart: unless-stopped
        image: client:latest
        ports:
            - 3000:3000
        volumes:
            - ./client:/usr/src/app
        links:
            - server
        command: yarn start
        tty: true
        stdin_open: true

    mongo:
        restart: unless-stopped
        image: mongo:3.6.17
        volumes:
            - mongo_data:/data/db
        ports:
            - 27017:27017